### ISSUE TITLE
Cannot get field 'tags' from type 'Post'. Field does not exist.

### ISSUE THREAD

**Issue by FilledStacks** [gridsome/gridsome-starter-blog#37]
I recently upgraded my gridsome version to Gridsome v0.7.2. 

**Dependencies:** Relating to mark down generation
"@gridsome/source-filesystem": "^0.3.0",
"@gridsome/transformer-remark": "^0.2.0",
"@gridsome/remark-prismjs": "^0.0.4",

Now when I try to run

```
gridsome develop
```
or
```
gridsome build
```

I get the following output.
```
Initializing plugins...
Tag > Failed to add node: Duplicate key for property id: Flutter
Tag > Failed to add node: Duplicate key for property id: Dependency Injection
Tag > Failed to add node: Duplicate key for property id: Provider
Load sources - 0.19s
Error: Cannot get field 'tags' from type 'Post'. Field does not exist.
    at ObjectTypeComposer.getField (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\graphql-compose\lib\ObjectTypeComposer.js:167:13)
    at ObjectTypeComposer.isFieldPlural (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\graphql-compose\lib\ObjectTypeComposer.js:365:23)
    at mapValues (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\graphql\nodes\index.js:260:25)
    at D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\lodash\lodash.js:13401:38
    at D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\lodash\lodash.js:4905:15
    at baseForOwn (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\lodash\lodash.js:2990:24)
    at mapValues (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\lodash\lodash.js:13400:7)
    at createReferenceFields (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\graphql\nodes\index.js:257:16)
    at createNodesSchema (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\graphql\nodes\index.js:30:5)
    at createSchema (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\graphql\createSchema.js:59:3)
    at Schema.buildSchema (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\app\Schema.js:28:28)
    at Plugins.createSchema (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\app\Plugins.js:93:22)
```

Here is my gridsome.config.js: 

```
module.exports = {
  siteName: "FilledStacks",
  siteDescription: "Flutter and Mobile development tutorials and guides",
  siteUrl: "https://www.filledstacks.com",
  plugins: [
   ...
    {
      // Create posts from markdown files
      use: "@gridsome/source-filesystem",
      options: {
        typeName: "Post",
        path: "content/posts/*.md",
        route: "post/:slug",
        refs: {
          // Creates a GraphQL collection from 'tags' in front-matter and adds a reference.
          tags: {
            typeName: "Tag",
            route: "/tag/:id",
            create: true
          }
        }
      }
    },
    ...
    }
  ],

  transformers: {
    //Add markdown support to all file-system sources
    remark: {
      externalLinksTarget: "_blank",
      externalLinksRel: ["nofollow", "noopener", "noreferrer"],
      anchorClassName: "icon icon-link",
      autolinkHeadings: true,
      plugins: ["@gridsome/remark-prismjs"]
    }
  }
};

```

And in all of my markdown files I have tags in the frontmatter.

```
---
title: Flutter Architecture - ScopedModel implementation Guide
date: 2019-04-21
published: true
cover_image: ../images/007/007.jpg
tags: ["Flutter","Architecture", "ScopedModel"]
videoLink: https://www.youtube.com/embed/JsjDLHxGz4M
canonical_url: true
description: "A clear and direct guide to writing and maintaining a production ready application in Flutter using the ScopedModel architecture."
---
```

Is there anything that I need to change after the update that I might have missed. I went from 0.5.8 -> 0.7.2 and attempted to add the gridsome/vue-remark plugin as well.

**Comment by FilledStacks** [comment]
Quick update:

I cloned this repo, then I executed the following command

```
yarn upgrade gridsome --latest
```

Then I got the same error. No other changes. Any help would be appreciated.

**Comment by FilledStacks** [comment]
Upgrading all the gridsome/ plugins got it working again.
