### ISSUE TITLE
Getting errors when installing npm packages in both Ubuntu WSL and Windows 11

### ISSUE THREAD

**Issue by SasikaA073** [gridsome/gridsome-starter-blog#63]
I referred to this documentation. ( https://ghost.org/docs/jamstack/gridsome/ )

First I used Ubuntu WSL terminal to start working. I have used Gatsby before in this platform. I haven't got any errors there. 
According to the docs, I ran this command. 

`npm install -g @gridsome/cli`
then I got this message saying there are 4 moderate vulnerabilities. 

```
added 182 packages, and audited 183 packages in 19s

15 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

After running `npm audit` I got this.  `found 0 vulnerabilities`

Because there were zero vulnerabilities, I proceeded with the documentation. Then ran this command.
`gridsome create gridsome-ghost https://github.com/gridsome/gridsome-starter-blog.git`

Then got this error message 
```
> Clone https://github.com/gridsome/gridsome-starter-blog.git 3.83s
> Update project package.json 0s
> Install dependencies
  • Building fresh packages (4 of 4)
Error: Failed to install dependencies with yarn. Please enter gridsome-ghost directory and install dependencies with yarn or npm manually. Then run gridsome develop to start local development.

    Exit code 1
    at ChildProcess.<anonymous> (C:\Users\Sasika\AppData\Roaming\npm\node_modules\@gridsome\cli\lib\commands\create.js:106:17)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.cp.emit (C:\Users\Sasika\AppData\Roaming\npm\node_modules\@gridsome\cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```
Then I entered to the gridsome-ghost directory and run 'npm install' and it also gave errors. 

Then after ignoring these error messages, I tried this command `gridsome develop`. Then I got this result.

```
Gridsome v0.7.23

Initializing plugins...
Load sources - 0.05s
Create GraphQL schema - 0.05s
Create pages and templates - 0.07s
Generate temporary code - 0.08s
Bootstrap finish - 2.56s


 ERROR  Failed to compile with 9 errors                                                                      11:37:26 PM

 ERROR  Failed to compile with 9 errors                                                                      11:37:26 PM

 error  in ./src/assets/style/index.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getDefaultSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/index.js:40:61)

 @ ./src/assets/style/index.scss 4:14-216 15:3-20:5 16:22-224
 @ ./src/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/Post.vue?vue&type=style&index=0&id=8099c222&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getDefaultSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/index.js:40:61)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/templates/Post.vue?vue&type=style&index=0&id=8099c222&lang=scss& 4:14-429 15:3-20:5 16:22-437
 @ ./src/templates/Post.vue?vue&type=style&index=0&id=8099c222&lang=scss&
 @ ./src/templates/Post.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/layouts/Default.vue?vue&type=style&index=0&id=c6c5ef5c&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getDefaultSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/index.js:40:61)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/Default.vue?vue&type=style&index=0&id=c6c5ef5c&lang=scss& 4:14-432 15:3-20:5 16:22-440
 @ ./src/layouts/Default.vue?vue&type=style&index=0&id=c6c5ef5c&lang=scss&
 @ ./src/layouts/Default.vue
 @ ./src/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/components/Logo.vue?vue&type=style&index=0&id=4ef0a45b&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getDefaultSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/index.js:40:61)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Logo.vue?vue&type=style&index=0&id=4ef0a45b&lang=scss& 4:14-429 15:3-20:5 16:22-437
 @ ./src/components/Logo.vue?vue&type=style&index=0&id=4ef0a45b&lang=scss&
 @ ./src/components/Logo.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue
 @ ./src/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/components/ToggleTheme.vue?vue&type=style&index=0&id=51f78a55&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getDefaultSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/index.js:40:61)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/ToggleTheme.vue?vue&type=style&index=0&id=51f78a55&lang=scss& 4:14-436 15:3-20:5 16:22-444
 @ ./src/components/ToggleTheme.vue?vue&type=style&index=0&id=51f78a55&lang=scss&
 @ ./src/components/ToggleTheme.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue
 @ ./src/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/components/Author.vue?vue&type=style&index=0&id=dafbeb8a&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getDefaultSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/index.js:40:61)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Author.vue?vue&type=style&index=0&id=dafbeb8a&lang=scss& 4:14-431 15:3-20:5 16:22-439
 @ ./src/components/Author.vue?vue&type=style&index=0&id=dafbeb8a&lang=scss&
 @ ./src/components/Author.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/templates/Tag.vue?vue&type=script&lang=js&
 @ ./src/templates/Tag.vue?vue&type=script&lang=js&
 @ ./src/templates/Tag.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/components/PostCard.vue?vue&type=style&index=0&id=040ef000&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getDefaultSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/index.js:40:61)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/PostCard.vue?vue&type=style&index=0&id=040ef000&lang=scss& 4:14-433 15:3-20:5 16:22-441
 @ ./src/components/PostCard.vue?vue&type=style&index=0&id=040ef000&lang=scss&
 @ ./src/components/PostCard.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/templates/Tag.vue?vue&type=script&lang=js&
 @ ./src/templates/Tag.vue?vue&type=script&lang=js&
 @ ./src/templates/Tag.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/components/PostMeta.vue?vue&type=style&index=0&id=2c99ef16&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getDefaultSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/index.js:40:61)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/PostMeta.vue?vue&type=style&index=0&id=2c99ef16&lang=scss& 4:14-433 15:3-20:5 16:22-441
 @ ./src/components/PostMeta.vue?vue&type=style&index=0&id=2c99ef16&lang=scss&
 @ ./src/components/PostMeta.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/templates/Post.vue?vue&type=script&lang=js&
 @ ./src/templates/Post.vue?vue&type=script&lang=js&
 @ ./src/templates/Post.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/components/PostTags.vue?vue&type=style&index=0&id=4fde06ee&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/sasika/blog/gridsome-ghost/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getDefaultSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/sasika/blog/gridsome-ghost/node_modules/sass-loader/dist/index.js:40:61)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/PostTags.vue?vue&type=style&index=0&id=4fde06ee&lang=scss& 4:14-433 15:3-20:5 16:22-441
 @ ./src/components/PostTags.vue?vue&type=style&index=0&id=4fde06ee&lang=scss&
 @ ./src/components/PostTags.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/templates/Post.vue?vue&type=script&lang=js&
 @ ./src/templates/Post.vue?vue&type=script&lang=js&
 @ ./src/templates/Post.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js


```
____

Then I tried this workflow using yarn in Ubuntu WSL, but no difference. I get the same error message every time. 

___

Then I tried this workflow in Windows 11 command prompt. I got the same error messages.

**Comment by IMujagic** [comment]
I can confirm this for Windows 11 + Ubuntu container (CI/CD runner).
I have tried to install packages using yarn, but it didn't help. 

Node version: 18.13.0
NPM version: 9.2.0

Creating gridsome website without the starter template works as expected. By using this starter template I get the errors on npm i.
